services:
  gold:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gold-price
    restart: unless-stopped
    ports:
      - "8080:5000"
    networks:
      - internal

  redis:
    image: redis:7
    container_name: goldapi-redis
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    driver: bridge
